<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Service;
use App\Models\Rashi;
use App\Models\Festival;
use App\Models\Ebook;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Admin
        User::create(['name'=>'Admin','email'=>'admin@vedmitra.in','password'=>Hash::make('Admin@12345'),'role'=>'admin','account_status'=>'active']);

        // Services
        foreach ([
            ['name'=>'Griha Pravesh','description'=>'Housewarming ceremony','base_price'=>3100,'duration_hours'=>3],
            ['name'=>'Satyanarayan Katha','description'=>'Lord Vishnu puja for prosperity','base_price'=>2100,'duration_hours'=>2],
            ['name'=>'Marriage Ceremony','description'=>'Complete Vedic wedding rituals','base_price'=>11000,'duration_hours'=>8],
            ['name'=>'Ganesh Puja','description'=>'Lord Ganesh worship','base_price'=>1100,'duration_hours'=>1],
            ['name'=>'Laxmi Puja','description'=>'Goddess Laxmi puja for wealth','base_price'=>1500,'duration_hours'=>2],
            ['name'=>'Mundan Ceremony','description'=>'First head-shaving ceremony','base_price'=>2500,'duration_hours'=>2],
            ['name'=>'Navgrah Shanti','description'=>'Planetary peace puja','base_price'=>3500,'duration_hours'=>3],
            ['name'=>'Rudrabhishek','description'=>'Lord Shiva abhishek','base_price'=>5100,'duration_hours'=>3],
        ] as $s) { Service::create($s); }

        // 12 Rashis
        foreach ([
            ['name'=>'Aries','hindi_name'=>'मेष','symbol'=>'♈','element'=>'Fire','lucky_color'=>'Red','lucky_number'=>'9','daily_prediction'=>'Today brings new energy and opportunities. Take initiative in pending tasks. Your confidence will attract positive outcomes.','weekly_prediction'=>'This week favors bold decisions. Career growth is indicated mid-week.','monthly_prediction'=>'A transformative month ahead with financial gains.','career_prediction'=>'Leadership opportunities emerge. Stay focused on goals.','health_prediction'=>'Pay attention to headaches. Regular exercise recommended.','relationship_prediction'=>'Romance flourishes. Express your feelings openly.'],
            ['name'=>'Taurus','hindi_name'=>'वृषभ','symbol'=>'♉','element'=>'Earth','lucky_color'=>'Green','lucky_number'=>'6','daily_prediction'=>'Financial stability improves today. A good day for investments and savings. Stay grounded in your approach.','weekly_prediction'=>'Material comforts increase this week. Avoid unnecessary spending.','monthly_prediction'=>'Steady progress in career and finances this month.','career_prediction'=>'Patience pays off in professional life.','health_prediction'=>'Throat and neck need care. Stay hydrated.','relationship_prediction'=>'Stability in relationships. Plan quality time together.'],
            ['name'=>'Gemini','hindi_name'=>'मिथुन','symbol'=>'♊','element'=>'Air','lucky_color'=>'Yellow','lucky_number'=>'5','daily_prediction'=>'Communication is your strength today. Network actively and share your ideas. A message brings good news.','weekly_prediction'=>'Social connections bring opportunities this week.','monthly_prediction'=>'An intellectually stimulating month with travel possibilities.','career_prediction'=>'Media and communication roles are favored.','health_prediction'=>'Breathing exercises will help. Avoid overthinking.','relationship_prediction'=>'Open dialogue strengthens bonds. Listen more.'],
            ['name'=>'Cancer','hindi_name'=>'कर्क','symbol'=>'♋','element'=>'Water','lucky_color'=>'White','lucky_number'=>'2','daily_prediction'=>'Emotional intelligence guides you today. Family matters take priority. Trust your intuition for important decisions.','weekly_prediction'=>'Home improvements bring joy. Family bonds strengthen.','monthly_prediction'=>'A nurturing month focused on emotional well-being.','career_prediction'=>'Healthcare and education fields bring success.','health_prediction'=>'Digestive health needs attention. Eat mindfully.','relationship_prediction'=>'Deep emotional connections form. Be vulnerable.'],
            ['name'=>'Leo','hindi_name'=>'सिंह','symbol'=>'♌','element'=>'Fire','lucky_color'=>'Gold','lucky_number'=>'1','daily_prediction'=>'Your charisma is at its peak today. Take center stage in professional matters. Recognition and praise are coming your way.','weekly_prediction'=>'Creative projects succeed this week. Leadership roles beckon.','monthly_prediction'=>'A month of recognition and achievement awaits.','career_prediction'=>'Entertainment and management roles suit you.','health_prediction'=>'Heart health is important. Regular cardio recommended.','relationship_prediction'=>'Your warmth attracts admirers. Be generous with love.'],
            ['name'=>'Virgo','hindi_name'=>'कन्या','symbol'=>'♍','element'=>'Earth','lucky_color'=>'Green','lucky_number'=>'5','daily_prediction'=>'Attention to detail brings rewards today. Organize your workspace and plan ahead. Health improvements are noticeable.','weekly_prediction'=>'Analytical skills shine this week. Problem-solving brings recognition.','monthly_prediction'=>'A productive month with health breakthroughs.','career_prediction'=>'Research and analytical roles are favored.','health_prediction'=>'Focus on gut health. Add probiotics to diet.','relationship_prediction'=>'Show affection through service and care.'],
            ['name'=>'Libra','hindi_name'=>'तुला','symbol'=>'♎','element'=>'Air','lucky_color'=>'Pink','lucky_number'=>'6','daily_prediction'=>'Balance and harmony define today. Partnerships flourish. Artistic pursuits bring satisfaction and potential income.','weekly_prediction'=>'Diplomacy skills resolve conflicts. Beauty-related activities are favored.','monthly_prediction'=>'A harmonious month for relationships and partnerships.','career_prediction'=>'Law, art, and design fields bring success.','health_prediction'=>'Lower back needs care. Practice good posture.','relationship_prediction'=>'Partnerships strengthen. Compromise leads to happiness.'],
            ['name'=>'Scorpio','hindi_name'=>'वृश्चिक','symbol'=>'♏','element'=>'Water','lucky_color'=>'Maroon','lucky_number'=>'8','daily_prediction'=>'Deep insights come naturally today. Research and investigation yield results. Transformation energy is strong.','weekly_prediction'=>'Hidden truths surface this week. Trust your instincts.','monthly_prediction'=>'A powerful month of transformation and rebirth.','career_prediction'=>'Investigation and research roles bring breakthroughs.','health_prediction'=>'Emotional detox needed. Practice meditation.','relationship_prediction'=>'Intensity deepens connections. Trust is essential.'],
            ['name'=>'Sagittarius','hindi_name'=>'धनु','symbol'=>'♐','element'=>'Fire','lucky_color'=>'Purple','lucky_number'=>'3','daily_prediction'=>'Adventure calls today. Travel plans materialize. Higher learning and philosophical discussions bring fulfillment.','weekly_prediction'=>'Expansion in knowledge and travel this week.','monthly_prediction'=>'An adventurous month with educational opportunities.','career_prediction'=>'Teaching, travel, and publishing are favored.','health_prediction'=>'Thigh and hip flexibility exercises recommended.','relationship_prediction'=>'Freedom-loving energy. Respect each other\'s space.'],
            ['name'=>'Capricorn','hindi_name'=>'मकर','symbol'=>'♑','element'=>'Earth','lucky_color'=>'Brown','lucky_number'=>'8','daily_prediction'=>'Discipline and hard work pay off today. Career ambitions advance. Authority figures notice your dedication.','weekly_prediction'=>'Professional achievements highlight this week.','monthly_prediction'=>'A career-defining month with promotion possibilities.','career_prediction'=>'Management and government roles suit you.','health_prediction'=>'Bone and joint health is priority. Take calcium supplements.','relationship_prediction'=>'Commitment deepens. Long-term plans solidify.'],
            ['name'=>'Aquarius','hindi_name'=>'कुम्भ','symbol'=>'♒','element'=>'Air','lucky_color'=>'Blue','lucky_number'=>'4','daily_prediction'=>'Innovation and originality shine today. Technology-related projects succeed. Community involvement brings fulfillment.','weekly_prediction'=>'Humanitarian efforts bring recognition this week.','monthly_prediction'=>'A month of innovation and social impact.','career_prediction'=>'Technology and social work fields are favorable.','health_prediction'=>'Circulation needs attention. Stay active and warm.','relationship_prediction'=>'Friendship-based love thrives. Be your authentic self.'],
            ['name'=>'Pisces','hindi_name'=>'मीन','symbol'=>'♓','element'=>'Water','lucky_color'=>'Sea Green','lucky_number'=>'7','daily_prediction'=>'Spiritual awareness heightens today. Creative inspiration flows freely. Dreams carry meaningful messages.','weekly_prediction'=>'Artistic talents bring appreciation and income this week.','monthly_prediction'=>'A deeply spiritual and creative month awaits.','career_prediction'=>'Arts, healing, and spiritual services are favored.','health_prediction'=>'Foot care important. Swimming is excellent exercise.','relationship_prediction'=>'Soulmate connections deepen. Trust the universe.'],
        ] as $r) { Rashi::create(array_merge($r, ['prediction_date' => now()])); }

        // Festivals 2026
        foreach ([
            ['title'=>'Makar Sankranti','festival_date'=>'2026-01-14','category'=>'festival','is_major'=>true,'tithi'=>'Magha Krishna','description'=>'Harvest festival celebrating the Sun\'s transit into Capricorn. Devotees take holy dips and fly kites.'],
            ['title'=>'Basant Panchami','festival_date'=>'2026-01-24','category'=>'festival','is_major'=>true,'tithi'=>'Magha Shukla Panchami','description'=>'Festival of spring dedicated to Goddess Saraswati, the deity of knowledge and arts.'],
            ['title'=>'Maha Shivaratri','festival_date'=>'2026-02-15','category'=>'vrat','is_major'=>true,'tithi'=>'Phalguna Krishna Chaturdashi','description'=>'The great night of Lord Shiva. Devotees observe fast and perform Rudrabhishek throughout the night.'],
            ['title'=>'Holi','festival_date'=>'2026-03-17','category'=>'festival','is_major'=>true,'tithi'=>'Phalguna Purnima','description'=>'Festival of colors celebrating the victory of good over evil and the arrival of spring.'],
            ['title'=>'Chaitra Navratri','festival_date'=>'2026-03-28','category'=>'festival','is_major'=>true,'tithi'=>'Chaitra Shukla Pratipada','description'=>'Nine nights dedicated to Goddess Durga. Marks the beginning of Hindu New Year.'],
            ['title'=>'Ram Navami','festival_date'=>'2026-04-05','category'=>'festival','is_major'=>true,'tithi'=>'Chaitra Shukla Navami','description'=>'Birthday of Lord Rama, the seventh avatar of Lord Vishnu.'],
            ['title'=>'Hanuman Jayanti','festival_date'=>'2026-04-14','category'=>'festival','is_major'=>false,'tithi'=>'Chaitra Purnima','description'=>'Birthday celebration of Lord Hanuman, the devotee of Lord Rama.'],
            ['title'=>'Akshaya Tritiya','festival_date'=>'2026-04-26','category'=>'tithi','is_major'=>true,'tithi'=>'Vaishakha Shukla Tritiya','description'=>'Most auspicious day for new beginnings, investments, and gold purchase.'],
            ['title'=>'Buddha Purnima','festival_date'=>'2026-05-12','category'=>'festival','is_major'=>false,'tithi'=>'Vaishakha Purnima','description'=>'Celebrates the birth, enlightenment, and death of Lord Buddha.'],
            ['title'=>'Guru Purnima','festival_date'=>'2026-07-10','category'=>'festival','is_major'=>false,'tithi'=>'Ashadha Purnima','description'=>'Day to honor and express gratitude towards spiritual teachers and gurus.'],
            ['title'=>'Raksha Bandhan','festival_date'=>'2026-08-08','category'=>'festival','is_major'=>true,'tithi'=>'Shravana Purnima','description'=>'Festival celebrating the bond between brothers and sisters.'],
            ['title'=>'Janmashtami','festival_date'=>'2026-08-22','category'=>'festival','is_major'=>true,'tithi'=>'Bhadrapada Krishna Ashtami','description'=>'Birthday of Lord Krishna, celebrated with fasting, devotion, and Dahi Handi.'],
            ['title'=>'Ganesh Chaturthi','festival_date'=>'2026-09-06','category'=>'festival','is_major'=>true,'tithi'=>'Bhadrapada Shukla Chaturthi','description'=>'Festival celebrating the birth of Lord Ganesha with clay idol installations.'],
            ['title'=>'Jivitputrika Vrat','festival_date'=>'2026-09-19','category'=>'vrat','is_major'=>true,'tithi'=>'Ashwin Krishna Ashtami','description'=>'Mothers observe strict fast for the well-being and long life of their children.'],
            ['title'=>'Sharad Navratri','festival_date'=>'2026-10-07','category'=>'festival','is_major'=>true,'tithi'=>'Ashwin Shukla Pratipada','description'=>'Nine nights of Goddess Durga worship with Garba and Dandiya celebrations.'],
            ['title'=>'Dussehra','festival_date'=>'2026-10-16','category'=>'festival','is_major'=>true,'tithi'=>'Ashwin Shukla Dashami','description'=>'Victory of Lord Rama over Ravana. Effigies of Ravana are burnt across India.'],
            ['title'=>'Karwa Chauth','festival_date'=>'2026-10-26','category'=>'vrat','is_major'=>true,'tithi'=>'Kartik Krishna Chaturthi','description'=>'Married women fast from sunrise to moonrise for the longevity of their husbands.'],
            ['title'=>'Diwali','festival_date'=>'2026-11-05','category'=>'festival','is_major'=>true,'tithi'=>'Kartik Amavasya','description'=>'Festival of lights celebrating Lord Rama\'s return to Ayodhya. Houses are decorated with diyas and rangoli.'],
            ['title'=>'Govardhan Puja','festival_date'=>'2026-11-06','category'=>'festival','is_major'=>false,'tithi'=>'Kartik Shukla Pratipada','description'=>'Celebrates Lord Krishna lifting Govardhan Hill to protect villagers.'],
            ['title'=>'Chhath Puja','festival_date'=>'2026-11-08','category'=>'festival','is_major'=>true,'tithi'=>'Kartik Shukla Shashthi','description'=>'Ancient Vedic festival dedicated to Sun God. Devotees offer prayers standing in water.'],
            ['title'=>'Dev Diwali','festival_date'=>'2026-11-19','category'=>'festival','is_major'=>false,'tithi'=>'Kartik Purnima','description'=>'Festival of lights celebrated by the Gods. Ghats of Varanasi are illuminated.'],
        ] as $f) { Festival::create($f); }

        // E-Books
        foreach ([
            ['title'=>'Hanuman Chalisa','category'=>'aarti','description'=>'Sacred 40 verses praising Lord Hanuman, composed by Goswami Tulsidas.','content'=>"श्रीगुरु चरन सरोज रज, निज मनु मुकुरु सुधारि।\nबरनउँ रघुबर बिमल जसु, जो दायकु फल चारि॥\n\nबुद्धिहीन तनु जानिके, सुमिरौं पवन-कुमार।\nबल बुद्धि बिद्या देहु मोहिं, हरहु कलेस बिकार॥\n\nजय हनुमान ज्ञान गुन सागर। जय कपीस तिहुँ लोक उजागर॥\nराम दूत अतुलित बल धामा। अंजनि-पुत्र पवनसुत नामा॥\nमहाबीर बिक्रम बजरंगी। कुमति निवार सुमति के संगी॥\nकंचन बरन बिराज सुबेसा। कानन कुंडल कुंचित केसा॥\nहाथ बज्र औ ध्वजा बिराजै। काँधे मूँज जनेऊ साजै॥\nशंकर सुवन केसरीनंदन। तेज प्रताप महा जग बंदन॥\nबिद्यावान गुनी अति चातुर। राम काज करिबे को आतुर॥\nप्रभु चरित्र सुनिबे को रसिया। राम लखन सीता मन बसिया॥"],
            ['title'=>'Durga Chalisa','category'=>'aarti','description'=>'40 verses in praise of Goddess Durga for strength and protection.','content'=>"नमो नमो दुर्गे सुख करनी। नमो नमो अम्बे दुःख हरनी॥\nनिराकार है ज्योति तुम्हारी। तिहूँ लोक फैली उजियारी॥\n\nशशि ललाट मुख महाविशाला। नेत्र लाल भृकुटी विकराला॥\nरूप मातु को अधिक सुहावे। दरश करत जन अति सुख पावे॥"],
            ['title'=>'Shiv Chalisa','category'=>'aarti','description'=>'Sacred 40 verses praising Lord Shiva for peace and moksha.','content'=>"जय गिरिजा पति दीनदयाला। सदा करत संतन प्रतिपाला॥\nभाल चन्द्रमा सोहत नीके। कानन कुण्डल नागफनी के॥\n\nअंग गौर शिर गंगा बहाये। मुण्डमाल तन क्षार लगाये॥\nवस्त्र खाल बाघम्बर सोहे। छवि को देख नाग मुनि मोहे॥"],
            ['title'=>'Satyanarayan Vrat Katha','category'=>'katha','description'=>'Complete Satyanarayan Katha with all five chapters for prosperity and well-being.','content'=>"श्री सत्यनारायण व्रत कथा\n\nप्रथम अध्याय:\nएक समय नैमिषारण्य में शौनकादि अठ्ठासी हजार ऋषि-मुनियों ने सूतजी से पूछा - हे सूतजी! संसार के लोगों के कष्ट और दरिद्रता दूर करने का कोई सरल उपाय बताइए।\n\nसूतजी बोले - हे ऋषियों! एक बार भगवान विष्णु से नारद जी ने भी यही प्रश्न किया था। तब भगवान ने कहा कि सत्यनारायण भगवान की कथा सुनने और व्रत करने से मनुष्य के सभी पाप नष्ट हो जाते हैं।"],
            ['title'=>'Jivitputrika Vrat Katha','category'=>'katha','description'=>'Complete Jivitputrika/Jiutiya Vrat Katha observed by mothers for children\'s long life.','content'=>"जीवित्पुत्रिका व्रत कथा\n\nप्राचीन काल में एक राजा की दो रानियां थीं। बड़ी रानी के सात पुत्र थे और छोटी रानी के एक पुत्र। छोटी रानी बड़ी सीधी और धर्मपरायण थी।\n\nएक बार जीवित्पुत्रिका व्रत आया। बड़ी रानी ने व्रत तो रखा परन्तु विधि-विधान का पालन नहीं किया। छोटी रानी ने पूरी श्रद्धा से व्रत रखा और पूजा विधि का पालन किया।\n\nइस व्रत के प्रभाव से छोटी रानी का पुत्र दीर्घायु हुआ।"],
            ['title'=>'Ramayana Saar','category'=>'scripture','description'=>'Summary of the great epic Ramayana by Maharishi Valmiki, covering all seven Kandas.','content'=>"श्रीरामचरितमानस सार\n\nबालकाण्ड: भगवान राम का जन्म अयोध्या में राजा दशरथ और रानी कौशल्या के यहां हुआ। गुरु विश्वामित्र के साथ राम और लक्ष्मण ताड़का वध और यज्ञ रक्षा के लिए गए। जनकपुर में सीता स्वयंवर में शिव धनुष तोड़कर राम ने सीता से विवाह किया।\n\nअयोध्याकाण्ड: कैकेयी के वरदान के कारण राम को 14 वर्ष का वनवास मिला। सीता और लक्ष्मण भी उनके साथ वन गए। राजा दशरथ पुत्र वियोग में प्राण त्याग दिए।"],
        ] as $e) { Ebook::create($e); }

        $this->call(EbookLibrarySeeder::class);
    }
}
